// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:flutter_config/flutter_config.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.get('apiKeyweb'),
    appId: dotenv.get('appIdweb'),
    messagingSenderId: dotenv.get('messagingSenderIdweb'),
    projectId: dotenv.get('projectIdweb'),
    authDomain: dotenv.get('authDomainweb'),
    databaseURL: dotenv.get('databaseURLweb'),
    storageBucket: dotenv.get('storageBucketweb'),
    measurementId: dotenv.get('measurementIdweb'),
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.get('apiKeyandroid'),
    appId: dotenv.get('apiIdandroid'),
    messagingSenderId: dotenv.get('messagingSenderIdandroid'),
    projectId: dotenv.get('projectIdandroid'),
    databaseURL: dotenv.get('databaseURLandroid'),
    storageBucket: dotenv.get('storageBucketandroid'),
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.get('apiKeyios'),
    appId: dotenv.get('appIdios'),
    messagingSenderId: dotenv.get('messagingSenderIdios'),
    projectId: dotenv.get('aprojectIdios'),
    databaseURL: dotenv.get('databaseURLios'),
    storageBucket: dotenv.get('storageBucketios'),
    iosClientId: dotenv.get('iosClientIdios'),
    iosBundleId: dotenv.get('iosBundleIdios'),
  );
}
