// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3bSVO9LZ4ecrzZH4fvFt3nrnPPGF5O0c',
    appId: '1:940102453608:web:62d46c19ab2cd83cea2edd',
    messagingSenderId: '940102453608',
    projectId: 'elementals-b304',
    authDomain: 'elementals-b304.firebaseapp.com',
    databaseURL: 'https://elementals-b304-default-rtdb.firebaseio.com',
    storageBucket: 'elementals-b304.appspot.com',
    measurementId: 'G-H8KTH00SVR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsPmlz-Xs7Y02viwyPW94avNLevCqxuho',
    appId: '1:940102453608:android:d5ef09f80829066fea2edd',
    messagingSenderId: '940102453608',
    projectId: 'elementals-b304',
    databaseURL: 'https://elementals-b304-default-rtdb.firebaseio.com',
    storageBucket: 'elementals-b304.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1LpxNTg5wcfKEOEmemoL8h8dQKhRkwII',
    appId: '1:940102453608:ios:c5e332f7ff97b5bdea2edd',
    messagingSenderId: '940102453608',
    projectId: 'elementals-b304',
    databaseURL: 'https://elementals-b304-default-rtdb.firebaseio.com',
    storageBucket: 'elementals-b304.appspot.com',
    iosClientId: '940102453608-tvs2i4jmp11hell460ar99ftq5bq75pm.apps.googleusercontent.com',
    iosBundleId: 'com.example.medcentral',
  );
}
